name: CI

on:
  push:
    branches: [ openraft-0.9 ]
  pull_request:
    branches: [ openraft-0.9 ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    strategy:
        matrix:
          toolchain:
            - stable
            
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
     
        
    - name: Install MSVC
      run: choco install visualstudio2022buildtools
    
    - name: Install Clang
      run: choco install llvm
    
    - name: Add libclang to PATH
      run: echo "C:/Program Files/LLVM/bin" >> $GITHUB_PATH

      
    - name: Build
      run: cargo build --release --verbose --target x86_64-pc-windows-msvc    
    
    - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: rxqlited.exe
          path: ./target/x86_64-pc-windows-msvc/release/rxqlited.exe